# Generated by Django 5.1.6 on 2025-02-08 18:39

import django.core.validators
import django.db.models.deletion
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=65, verbose_name='Numero da Peça')),
                ('name', models.CharField(max_length=127, verbose_name='Nome da Peça')),
                ('details', models.CharField(max_length=513, verbose_name='Detalhes da Peça')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço da Peça')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade de Peças')),
            ],
            options={
                'verbose_name': 'Peça',
                'verbose_name_plural': 'Peças',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.car', verbose_name='Carro')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parts.part', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Peça do carro',
                'verbose_name_plural': 'Peças dos carros',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
