# Generated by Django 5.1.6 on 2025-02-08 17:41

import django.core.validators
import django_lifecycle.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=127, verbose_name='Nome')),
                ('manufacturer', models.CharField(max_length=127, verbose_name='Fabricante')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)], verbose_name='Ano de Fabricação')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
